### ISSUE TITLE
how can i create multiple models 

### ISSUE THREAD

**Issue by prasad8mhatre** [afhaque/MeanMapAppV2.0#1]
I wanted to create two model in mongoose schema,but when i add one more model and attach that model to module.context it gives me a error:
http.js:690
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.

can you please help me ?

**Comment by afhaque** [comment]
Hey Prasad, 

Go ahead and post the code you're using in your Mongoose file. It will be easier for me to debug what you're trying to do. Usually, when I have multiple models, I create them each as their own Mongoose file and import them as separate variables in the express files where I need them.

Are you trying to use two models for the same mongodb collection? Or are these two models for completely separate collections?
